<?php

$modversion['name'] = _GBK_MODULE_NAME;
$modversion['version'] = 2.3;
$modversion['description'] = _GBK_MODULE_DESC;
$modversion['credits'] = 'Developped by Xtrem.dj@clubxtrem.net from http://www.clubxtrem.net';
$modversion['author'] = 'xtrem dj';
$modversion['help'] = 'top.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'casdedi_slogo.jpg';
$modversion['dirname'] = 'casdedi';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'casdedi';

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'casdedi_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'casdedi_sign.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'casdedi_post.html';
$modversion['templates'][3]['description'] = '';
